### ISSUE TITLE
cmake version includes alphabet characters

### ISSUE THREAD

**Issue by mehrangoli** [socrocket/core#1]
Hi,
I tried to build the SoCrocket project and i got the following error. I would really appreciate if I get any help to fix it.

./waf configure
Setting top to                           : /home/mehran/clang-llvm/gdb/TLM2_detail_extraction/core-master 
Setting out to                           : /home/mehran/clang-llvm/gdb/TLM2_detail_extraction/core-master/build 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for program 'python'            : /usr/bin/python 
Checking for waf version in 1.6.0-1.9.0  : ok 
Checking for python version              : (2, 7, 10, 'final', 0) 
python-config                            : /usr/bin/python-config 
Asking python-config for pyembed '--cflags --libs --ldflags' flags : yes 
Testing pyembed configuration                                      : yes 
Asking python-config for pyext '--cflags --libs --ldflags' flags   : yes 
Testing pyext configuration                                        : yes 

      To compile SoCRocket you need to have installed a basic Unix system.
      Atleast it needs to contain: 

        nm, git, patch, make, wget / curl, tar, ln, bash ans swig, python.

      Moreover you will need the development packages from readline:

        libreadline-dev

      Furthermore you need to provide cross compiler for sparc. If not provided
      we will try to fetch them from Gaisler (sparc-elf-gcc). But you will need 
      to provice a 32bit environment to execute the precompiled toolchain.

      For the ipython support blas and lapack needs to be installed.
    
Checking for program 'nm'                                          : /usr/bin/nm 
Checking for program 'git'                                         : /usr/bin/git 
Checking for program 'patch'                                       : /usr/bin/patch 
Checking for program 'make'                                        : /usr/bin/make 
Checking for program 'wget'                                        : /usr/bin/wget 
Checking for program 'tar'                                         : /usr/bin/tar 
Checking for program 'ln'                                          : /usr/bin/ln 
Checking for program 'bash'                                        : /usr/bin/bash 
Checking for linker flags -pthread                                 : yes 
Checking for compiler flags -pthread                               : yes 
Checking for compiler version                                      : ok - 5.3.1 
Determining gcc search path                                        : ok 
Checking for g++ optimization flags                                : yes 
Checking for gcc optimization flags                                : yes 
Checking for C compilation flags                                   : yes 
Checking for C compilation flags                                   : yes 
Checking for C++ compilation flags                                 : yes 
Checking for link flags                                            : yes 
Checking boost includes                                            : 1.57.0 
boost: static parameter is deprecated, use stlib instead.
Checking boost libs                                                : ok 
Checking for boost linkage                                         : ok 
Checking for host endianness                                       : little 
Checking for header cxxabi.h                                       : yes 
Checking for function abi::__cxa_demangle                          : yes 
Checking for static library elf                                    : not found 
Fetching libelf                                                    : Already done 
Extracting libelf                                                  : Already done 
Building libelf                                                    : Already done 
Checking for static library elf                                    : yes 
Checking for header libelf.h                                       : yes 
Checking for header gelf.h                                         : yes 
Checking for static library systemc                                : not found, compiling internal version. To use a system wide version use --with-systemc option 
Fetching systemc                                                   : Already done 
Extracting systemc                                                 : Already done 
Building systemc                                                   : Already done 
Checking for static library systemc                                : yes 
Checking for header systemc.h                                      : yes 
Checking for SystemC version                                       : yes 
Checking for SystemC Version 2.3.0+                                : yes 
Checking for header tlm.h                                          : yes 
Check for TLM version                                              : yes 
Checking for program 'cmake'                                       : /usr/local/bin/cmake 
Checking cmake version                                             : Traceback (most recent call last):
  File "/home/mehran/clang-llvm/gdb/TLM2_detail_extraction/core-master/.waf/waflib/Scripting.py", line 165, in waf_entry_point
    run_commands()
  File "/home/mehran/clang-llvm/gdb/TLM2_detail_extraction/core-master/.waf/waflib/Scripting.py", line 267, in run_commands
    ctx = run_command(cmd_name)
  File "/home/mehran/clang-llvm/gdb/TLM2_detail_extraction/core-master/.waf/waflib/Scripting.py", line 251, in run_command
    ctx.execute()
  File "/home/mehran/clang-llvm/gdb/TLM2_detail_extraction/core-master/.waf/waflib/Configure.py", line 165, in execute
    super(ConfigurationContext, self).execute()
  File "/home/mehran/clang-llvm/gdb/TLM2_detail_extraction/core-master/.waf/waflib/Context.py", line 226, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/mehran/clang-llvm/gdb/TLM2_detail_extraction/core-master/.waf/waflib/Context.py", line 304, in recurse
    user_function(self)
  File "/home/mehran/clang-llvm/gdb/TLM2_detail_extraction/core-master/wscript", line 36, in configure
    self.loadrepos()
  File "/home/mehran/clang-llvm/gdb/TLM2_detail_extraction/core-master/core/waf/common.py", line 79, in fun
    return f(*k,**kw)
  File "core/waf/repository.py", line 355, in loadrepos
    self.load(val, tooldir=[waf])
  File "/home/mehran/clang-llvm/gdb/TLM2_detail_extraction/core-master/.waf/waflib/Configure.py", line 270, in load
    if type(func) is type(Utils.readf): func(self)
  File "/home/mehran/clang-llvm/gdb/TLM2_detail_extraction/core-master/core/waf/cmake.py", line 56, in configure
    find(self)
  File "/home/mehran/clang-llvm/gdb/TLM2_detail_extraction/core-master/core/waf/cmake.py", line 42, in find
    cmake_version = [int(v) for v in cmake_version_str.split(" ")[2].split(".")]
ValueError: invalid literal for int() with base 10: '20151113-g73a3b'

**Comment by hackerhelmut** [comment]
Hi,

the problem seems to be that your cmake ist compiled from git. Please stick to a release or deinstall cmake to use an internal version.
Just for my curiosity what environment do you use? 
Distribution, SystemC etc.

Moreover I see you use clang as compiler, we never tried it.

Best regards
Rolf
